### ISSUE TITLE
clip error on non-standard fsw

### ISSUE THREAD

**Issue by RotemZilberman** [sign-language-processing/signwriting-evaluation#5]
clip return ValueError: Width and height must be >= 0 when the xy of the symbol is bigger than the box position.
list of invalid fsw from data.csv:
'M500x500S2ff00407x503S2a408430x588S18151422x565S16d18414x558S21100416x542S35d10420x523S2f900410x580', 'M500x500S2ff00407x502S14440435x545S2df07433x580S20318417x559S21100416x543S35d10420x522S2f900414x575', 'M500x500S2ff00407x501S1ce20436x535S2e300413x552S22b04418x565S36520420x523', 'M500x500S2ff00409x502S18602407x542S2490c438x546S35730417x524', 'M500x500S2ff00407x504S2e734435x574S11502423x557S2034a413x566S34610419x523S20500413x553S2f900414x584', 'M500x500S2ff00407x503S2990c440x553S36110417x524', 'M500x500S2ff00407x505S18600432x542S22a04435x574S36520420x527', 'M500x500S2ff00407x506S19a20421x547S26900426x571S34610419x525', 'M500x500S2ff00407x503S10120439x541S2a000415x563S28808409x547S35d10420x523', 'M500x500S2ff00407x502S1dc04428x543S2a008436x577S35d14420x523', 'M500x500S2ff00410x505S11a50436x540S2e304411x546S22b04408x561S35d14423x526', 'M500x500S2ff00407x505S22a04421x571S35010419x529', 'M500x500S2ff00407x505S1f432435x545S20300416x555S20500417x575S2f900419x529S35010407x570', 'M500x500S2ff00407x504S2e308429x558S36110417x525', 'M500x500S2ff00417x501S1ec18407x549S1ec10438x550S26504444x574S26514413x574S34510424x522S36a10447x519S20500417x535S20500445x579', 'M500x500S2ff00407x506S29204421x553S14a20434x547S34c10422x526', 'M500x500S2ff00407x505S2a00a418x559S34c10422x525', 'M500x500S2ff00412x505S14c20412x554S22520407x542S22b06422x585S35d10425x525', 'M500x500S2ff00407x504S26500440x557S35d10420x524', 'M500x500S2ff00412x504S1ee10428x562S1ee18407x557S26a00426x586S20500433x552S35d10425x524S2f900409x581', 'M500x500S2ff00407x502S19a20430x538S2e308432x562S35d14420x523', 'M500x500S2ff00407x502S14020427x533S23f0b411x555S35d14420x523', 'M500x500S2ff00407x501S18602412x548S26500445x538S35730415x523', 'M500x500S2ff00407x508S10c50427x549S22a04430x573S35d10420x528', 'M500x500S2ff00407x507S15230416x547S22b04419x581S34410420x529S22104434x546', 'M500x500S2ff00407x506S24904414x550S20320434x543S36110417x527', 'M500x500S2ff00407x504S26500440x557S33b10418x529', 'M500x500S2ff00407x508S22b00412x547S28c06416x552S33b10418x533', 'M500x500S2ff00407x501S29904442x565S35c10420x522', 'M500x500S2ff00407x504S1a020432x542S26900431x574S34c10422x524', 'M500x500S2ff00407x506S1a004428x552S22a04412x564S35010419x530', 'M500x500S2ff00407x504S23f09432x561S35d10420x524', 'M500x500S2ff00407x502S10e04426x546S26500443x546S35c10420x523', 'M500x500S2ff00407x502S23100430x559S35010419x526', 'M500x500S2ff00407x501S1ce20436x528S26900418x550S22a04437x561S36520420x523', 'M500x500S2ff00407x502S2df08436x559S19200433x537S34810413x524', 'M500x500S2ff00407x507S2a208411x582S17140407x545S15a36412x567S20500437x559S2f900419x531S35010407x580', 'M500x500S2ff00407x503S2920c441x534S22b00427x539S35010419x527', 'M500x500S2ff00410x506S10e04407x581S28900418x550S22b05424x555S35c10423x527', 'M500x500S2ff00407x501S26500445x540S34710418x524', 'M500x500S2ff00407x502S19220426x543S26500444x552S34810413x524', 'M500x500S2ff00407x505S17610435x540S22a04437x558S34410420x527', 'M500x500S2ff00407x504S11550426x542S26500440x547S35d10420x524', 'M500x500S2ff00407x501S10120443x528S23f0a418x553S35d10420x521'

**Comment by AmitMY** [comment]
fixed in https://github.com/sign-language-processing/signwriting/commit/0fdc36f0080df31b10fab06517a02516bfc2d58e
and https://github.com/sign-language-processing/signwriting-evaluation/commit/067555c15eba05dddda774ae61b47fb70cd5699b
